OBJS = \
	CatalogManager.o \
	Column.o \
	Table.o

all:$(OBJS)

CatalogManager.o:
	$(GXX) $(CFLAGS) -c CatalogManager.cpp -o $(BUILD)/CatalogManager.o

Column.o:
	$(GXX) $(CFLAGS) -c Column.cpp -o $(BUILD)/Column.o

Table.o:
	$(GXX) $(CFLAGS) -c Table.cpp -o $(BUILD)/Table.o