OBJS = \
	Interpreter.o \
	Condition.o \

all:$(OBJS)

Interpreter.o:
	$(GXX) $(CFLAGS) -c Interpreter.cpp -o $(BUILD)/Interpreter.o

Condition.o:
	$(GXX) $(CFLAGS) -c Condition.cpp -o $(BUILD)/Condition.o