OBJS = \
	Block.o \
	BufferManager.o \

all: $(OBJS)

Block.o:
	$(GXX) $(CFLAGS) -c Block.cpp -o $(BUILD)/Block.o

BufferManager.o:
	$(GXX) $(CFLAGS) -c BufferManager.cpp -o $(BUILD)/BufferManager.o

BufferTest.o:
	$(GXX) $(CFLAGS) -c bufferTest.cpp -o $(BUILD)/BufferTest.o